# Nom de votre projet
# (utilisez un seul mot, exemple: 'monprojet')
PROJECTNAME=testSing

# Fichiers sources
# Utilisez le suffixe .cpp pour les fichiers C++
# Listez tous les fichiers a compiler, separes par
# un espace. exemple: 'tp1.c tp2.cpp':
PRJSRC= testSing.cpp

include ../Makefile_Common_Tp
